// <auto-generated />
using System;
using Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datas.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250617074548_add rappels")]
    partial class addrappels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasTrigger("TG_UpdateCategorie");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Entities.Models.Rappel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DepenseFixeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RappelDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Vu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepenseFixeId");

                    b.ToTable("Rappels", null, t =>
                        {
                            t.HasTrigger("TG_UpdateRappel");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Entities.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Transaction");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Entities.Models.DepenseFixe", b =>
                {
                    b.HasBaseType("Entities.Models.Transaction");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstDomiciliée")
                        .HasColumnType("bit");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<int>("ReminderDaysBefore")
                        .HasColumnType("int");

                    b.ToTable("DepenseFixes", null, t =>
                        {
                            t.HasTrigger("TG_UpdateDepenseFix");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Entities.Models.TransactionVariable", b =>
                {
                    b.HasBaseType("Entities.Models.Transaction");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.ToTable("TransactionsVariables", null, t =>
                        {
                            t.HasTrigger("TG_UpdateTransaction");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Entities.Models.Rappel", b =>
                {
                    b.HasOne("Entities.Models.DepenseFixe", "DepenseFixe")
                        .WithMany("Rappels")
                        .HasForeignKey("DepenseFixeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepenseFixe");
                });

            modelBuilder.Entity("Entities.Models.Transaction", b =>
                {
                    b.HasOne("Entities.Models.Categorie", "Categorie")
                        .WithMany("Transactions")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Entities.Models.DepenseFixe", b =>
                {
                    b.HasOne("Entities.Models.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Entities.Models.DepenseFixe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.TransactionVariable", b =>
                {
                    b.HasOne("Entities.Models.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Entities.Models.TransactionVariable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Categorie", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Entities.Models.DepenseFixe", b =>
                {
                    b.Navigation("Rappels");
                });
#pragma warning restore 612, 618
        }
    }
}
